### ISSUE TITLE
Request Failed with Error 400 - Reset Accounts or Source

### ISSUE THREAD

**Issue by anoop-atre-sp** [yannick-beot-sp/vscode-sailpoint-identitynow#92] opened 2024-10-04 01:01 UTC
Error encountered while attempting a reset source and/or accounts using version "1.3.2" of the extension.

**Reset Source**
`Error running command vscode-sailpoint-identitynow.reset-source: Request failed with status code 400. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.reset-source.`

**Reset Accounts**
`Error running command vscode-sailpoint-identitynow.reset-source-accounts: Request failed with status code 400. This is likely caused by the extension that contributes vscode-sailpoint-identitynow.reset-source-accounts.` 

**Analysis Results**
Issue seems to be caused by one of the accounts in target source being correlated to an identity assigned as a source owner.

This was duplicated in Postman by attempting a reset of the source, but we get details about the 400 error in the request response.

```
{
    "detailCode": "400.1 Bad request content",
    "trackingId": "7fa2eefc55344d0ed61916b884cb20f7",
    "messages": [
        {
            "locale": "en-US",
            "localeOrigin": "DEFAULT",
            "text": "Action \"Remove Source Accounts\" cannot be performed on [1x1ffc3fa42743d6b20c94c6cd3fdb69]"
        },
        {
            "locale": "und",
            "localeOrigin": "REQUEST",
            "text": "Action \"Remove Source Accounts\" cannot be performed on [1x1ffc3fa42743d6b20c94c6cd3fdb69]"
        }
    ],
    "causes": [
        {
            "locale": "en-US",
            "localeOrigin": "DEFAULT",
            "text": "Source Owners account exists on source"
        }
    ]
}
```

**Possible Solution**
We will need to check if any of the accounts being removed are associated with an identity set as an "owner" in ISC (any source). Remove account association with identity and then reset the source or accounts.

**Error Handling**
Perhaps we could include the API response details in the extension console logs with the error code in the result notification. Postman includes the error details in the response which helped identify the root cause.

**Comment by anoop-atre-sp** [comment] 2024-10-09 19:06
Related Bug Report: https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/issues/85

**Comment by yannick-beot-sp** [comment] 2024-10-15 08:16
Duplicate of #85

**Closed by yannick-beot-sp** 2024-10-15 08:16 UTC
Labels: bug
