### ISSUE TITLE
Cannot save sources on any tenant

### ISSUE THREAD

**Issue by Tomartsh** [yannick-beot-sp/vscode-sailpoint-identitynow#67] opened 2024-02-20 08:00 UTC
**Describe the bug**
When I try to save any source on any tenant I get an error:
Failed to save 'SOURCE_NAME': Unable to write file 'idn://TENATN_URL/v3/sources/SOURCE_ID/SOURCE_NAME' (Error: The server did not find a current representation for the target resource.)

**To Reproduce**
1) open any source on any tenant
2) Do not change anything
3) Hit save (ctrl+s)
4) Voilla - the error mentioned

**Expected behavior**
Source should be saved without any issue

**Screenshots**
Please let me know if screenshots are required. This is pretty generic procedure and I am not comfortable sharing customer data.

**Environment**
Provide a screenshot of *Help* > *About*.
Attached in help-about.png

**Logs**
[vscode-app-1708415820850.log](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/files/14341146/vscode-app-1708415820850.log)
![Help-About](https://github.com/yannick-beot-sp/vscode-sailpoint-identitynow/assets/61180368/09a50515-4ed5-4475-b89b-7ce7e07648f6)

attaching vscode-app-1708415820850.log

**Additional context**
Well, pretty urgent as I cannot do anything with the source code.
Many thanks for this awesome tool by the way.
Much appreciated.

**Comment by yannick-beot-sp** [comment] 2024-02-20 13:46
Thank you @Tomartsh for opening an issue.
No recent change about that portion of code.
I will look into this.

**Comment by yannick-beot-sp** [comment] 2024-02-20 13:59
I can reproduce the 404 error outside VSCode.
It seems the issue is not in VSCode plugin.
I'll keep you posted.

**Comment by Tomartsh** [comment] 2024-02-20 14:02
postman ?
I did not try to be honest.
but others in the IdentityNow community reported experiencing the same issue

**Comment by yannick-beot-sp** [comment] 2024-03-15 12:53
I have been informed of the release of the fix in ISC.
The issue in ISC seems fixed in my tenant.

**Closed by yannick-beot-sp** 2024-03-15 12:53 UTC
Labels: bug
